language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build NgxGoogleMapHelper --base-href https://github.com/imanshu15/ngx-google-map-helper